# Generated by Django 5.2.7 on 2026-03-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_type', models.CharField(choices=[('url', 'URL'), ('email', 'Email'), ('phone', 'Phone'), ('contact', 'Contact'), ('pdf', 'PDF')], max_length=20)),
                ('data', models.TextField()),
                ('color', models.CharField(default='black', max_length=20)),
                ('qr_image', models.ImageField(upload_to='qr_codes/')),
                ('scans', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
